# Generated by Django 5.2.6 on 2025-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicationWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenreparacion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='AplicationWeb.servicio'),
        ),
    ]
